name: NDK build

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    env:
      module_id: mobile-ffmpeg
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: true
          lfs: true
          fetch-depth: "0"
      - name: Install Powershell
        run: sudo apt-get install -y powershell

      - name: Cache Android NDK
        id: cache-ndk
        uses: actions/cache@v2
        env:
          cache-name: cache-ndk
          ndkname: android-ndk-r22
        with:
          path: ndk
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.ndkname }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ env.ndkname }}

      - name: Install Android NDK
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        env:
          ndkname: android-ndk-r22
        run: |
          wget -q -O ndk.zip https://dl.google.com/android/repository/${ndkname}-linux-x86_64.zip
          unzip -q ndk.zip
          mv ${ndkname} ndk

      - name: Create ndkpath.txt
        run: |
          cd ndk
          pwd > ${GITHUB_WORKSPACE}/ndkpath.txt

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Enable untrusted output
        run: echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"

      #     - name: Cache QPM
      #       id: cache-qpm
      #       uses: actions/cache@v2
      #       env:
      #         cache-name: cache-qpm
      #       with:
      #         path: QPM
      #         key: ${{ runner.os }}-${{ env.cache-name }}-2
      #         restore-keys: |
      #           ${{ runner.os }}-${{ env.cache-name }}-2

      - name: Get QPM
        if: steps.cache-qpm.outputs.cache-hit != 'true'
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          name: QPM-ubuntu-x64
          path: QPM
          repo: sc2ad/QuestPackageManager

      #     - name: QPM Dependencies Cache
      #       id: cache-qpm-deps
      #       uses: actions/cache@v2
      #       env:
      #         cache-name: cache-qpm-deps
      #       with:
      #         path: ~/.config/QPM
      #         key: ${{ runner.os }}-${{ env.cache-name }}
      #         restore-keys: |
      #           ${{ runner.os }}-${{ env.cache-name }}

      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}

          # export ANDROID_HOME=~/.android/sdk
          export ANDROID_NDK_ROOT=$(cat ndkpath.txt)

          sudo apt install -y autotools-dev automake pkg-config autogen gperf

          chmod +x ./finalBuild.sh
          ./finalBuild.sh
      - name: The job has failed Build.log
        if: ${{ failure() }}
        run: |
          cat "mobile-ffmpeg/build.log"
          ls ./mobile-ffmpeg

      - name: Upload non-debug artifact
        uses: actions/upload-artifact@v2
        with:
          name: Prebuilt directory
          path: ./mobile-ffmpeg/prebuilt/
          if-no-files-found: error
